apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactive-movie-ingress
  namespace: reactive-movie-dev
spec:
  rules:
  - http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: reactive-movie-service
              port:
                number: 8080
