apiVersion: v1
kind: Service
metadata: 
  name: reactive-movie-service
  namespace: reactive-movie-dev
spec:
  selector:
    app: reactive-movie-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    