server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive
#    url: r2dbc:postgresql://${R2DBC_HOST}/${R2DBC_DB} #Por si se usa la db con docker
    username: postgres
    password: 1234
    
logging:
  level:
    root: INFO
    '[org.springframework.r2dbc]':   DEBUG
    reactor:
      netty:
        http:
          client: DEBUG